from ubuntu:latest
# ubuntu imageını kullanacağız

run echo "Hoş geldiniz DE Şubat grubu" > /root/hoşgeldiniz.txt
# imageın içine ne olacağını yazdık ve dosya yolunu verdik

cmd ["cat","/root/hoşgeldiniz.txt"]
# cat, linux komutudur ve dosyaya girmeden içinde ne olduğunu gösterir
# komutu ve komutun hangi dosya yolunda çalışması gerektiğini belirttik