version: '3'
services:
  nifi2:
    image: apache/nifi:1.13.1
    container_name: nifi-docker
    port:
      - 8080:8080
    volumes:
      -C:/Users/win10/Desktop/programlar/Data Engineering Bootcamp/DataEngineeringBootcamp/dockerFiles/data:/var/lib/data